function start

      %Figure and edit box
      hFig = uifigure;
      ax = axes('XLim',[-3 ,3],'YLim',[-3, 3],'ZLim',[-3 3]);

      
     
      
      %ellipse_position = [0.4 0.6 0.1 0.2];
     % ellipse_color=[1 1 1 ];
     % ellipse_h = annotation('ellipse',ellipse_position,...
                   % 'facecolor', ellipse_color);
   
     
     %Initializate Rotators, Reflector, PlugInBoards
     global R1, global R2,global R3,global Reflector,global PlugInBoard,global Numbers,global M ,global rectA,
     global rectB, global rectC, global rectD, global rectE ,global rectF, global rectG, global rectH, global rectI,
     global rectJ, global rectK, global rectL, global rectM, global rectN, global rectO, global rectP, global rectR,
     global rectQ, global rectS, global rectT, global rectU, global rectV, global rectW, global rectX, global rectY,
     global rectZ, global counter1, global counter2, global counter3, global counterTurnR1, global counterTurnR2, global counterTurnR3;
     R1=zeros(26);
     R2=zeros(26);
     R3=zeros(26);
     counterTurnR1=1;
     counterTurnR2=1;
     counterTurnR3=1;
     Reflector=zeros(26);
     PlugInBoard=zeros(26);
     Numbers=zeros(26,1);
     M=zeros(26);
    %[R1,R2,R3,Reflector, PlugInBoard,Numbers,M]=rotators(R1,R2,R3,Reflector, PlugInBoard,Numbers,M);
    rotators();
    
    rectRotator1 = annotation('textbox','Position', [.5 0.8 .12 .12],'String', 'A',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
  rectRotator2 = annotation('textbox', 'Position', [.3 0.8 .12 .12],'String', 'A',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
                 
   rectRotator3 = annotation('textbox', 'Position', [.1 0.8 .12 .12],'String', 'A',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
                 
    [dX,dMap]=imread('downArrow.jpg');
    downA=imresize(dX, [23 23]);   
   
    [uX,uMap]=imread('upArrow.jpg');
    upA=imresize(uX, [23 23]);  
   
    counter1=1;
    counter2=1;
    counter3=1;
    
   hDownR1= uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.625 0.80 0.052 0.065],...
             'Callback',@(~,~)fRotator(rectRotator1,1,1),...
            'cdata',downA);   
        
  hUpR1= uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.625 0.87 0.052 0.065],...
             'Callback',@(~,~)fRotator(rectRotator1,1,-1),...
             'cdata',upA);       
         
   hDownR2= uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.423 0.8 0.052 0.065],...
            'Callback',@(~,~)fRotator(rectRotator2,2,1),...
            'cdata',downA);   
        
  hUpR2= uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.423 0.87 0.052 0.065],...
            'Callback',@(~,~)fRotator(rectRotator2,2,-1),...
             'cdata',upA);     
         
  hDownR3= uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.223 0.8 0.052 0.065],...
            'Callback',@(~,~)fRotator(rectRotator3,3,1),...
            'cdata',downA);   
        
  hUpR3= uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.223 0.87 0.052 0.065],...
            'Callback',@(~,~)fRotator(rectRotator3,3,-1),...
             'cdata',upA);  
            

    

     
    
    rectQ = annotation('textbox', 'Position', [.10 0.6 .05 .05],'String', 'Q',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
                 
      rectW = annotation('textbox', 'Position', [.16 0.6 .05 .05],'String', 'W',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectE = annotation('textbox', 'Position', [.22 0.6 .05 .05],'String', 'E',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectR = annotation('textbox', 'Position', [.28 0.6 .05 .05],'String', 'R',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectT = annotation('textbox', 'Position', [.34 0.6 .05 .05],'String', 'T',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectZ = annotation('textbox', 'Position', [.4 0.6 .05 .05],'String', 'Z',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectU = annotation('textbox', 'Position', [.46 0.6 .05 .05],'String', 'U',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectI = annotation('textbox', 'Position', [.52 0.6 .05 .05],'String', 'I',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectO = annotation('textbox', 'Position', [.58 0.6 .05 .05],'String', 'O',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
      rectA = annotation('textbox', 'Position', [.16 0.54 .05 .05],'String', 'A',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectS = annotation('textbox', 'Position', [.22 0.54 .05 .05],'String', 'S',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectD = annotation('textbox', 'Position', [.28 0.54 .05 .05],'String', 'D',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectF = annotation('textbox', 'Position', [.34 0.54 .05 .05],'String', 'F',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectG = annotation('textbox', 'Position', [.4 0.54 .05 .05],'String', 'G',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectH = annotation('textbox', 'Position', [.46 0.54 .05 .05],'String', 'H',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectJ = annotation('textbox', 'Position', [.52 0.54 .05 .05],'String', 'J',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectK = annotation('textbox', 'Position', [.58 0.54 .05 .05],'String', 'K',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
      rectP = annotation('textbox', 'Position', [.10 0.48 .05 .05],'String', 'P',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
      rectY = annotation('textbox', 'Position', [.16 0.48 .05 .05],'String', 'Y',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectX = annotation('textbox', 'Position', [.22 0.48 .05 .05],'String', 'X',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectC = annotation('textbox', 'Position', [.28 0.48 .05 .05],'String', 'C',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectV = annotation('textbox', 'Position', [.34 0.48 .05 .05],'String', 'V',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectB = annotation('textbox', 'Position', [.4 0.48 .05 .05],'String', 'B',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectN = annotation('textbox', 'Position', [.46 0.48 .05 .05],'String', 'N',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectM = annotation('textbox', 'Position', [.52 0.48 .05 .05],'String', 'M',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     rectL = annotation('textbox', 'Position', [.58 0.48 .05 .05],'String', 'L',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
                 
     rectInput = annotation('textbox', 'Position', [.68 0.40 .3 .05],'String', 'Input',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
      hEditInput = uicontrol('Style','edit',...
                  'Units','normalized',...
                  'Position',[0.68 0.27 0.3 0.12],...
                  'String','');
              
      set(hEditInput,'Max',4);
      
      rectOutput = annotation('textbox', 'Position', [.68 0.6 .3 .05],'String', 'Output',...
                    'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
      hEditOutput = uicontrol('Style','edit',...
                  'Units','normalized',...
                  'Position',[0.68 0.47 0.3 0.12],...
                  'String','');
      set(hEditOutput,'Max',4);
      %Letters        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.10 0.4 0.05 0.05],...
            'String','Q',...
            'Callback',@(~,~)ClickButton('Q', hEditInput,hEditOutput,17,rectRotator1,rectRotator2, rectRotator3));        

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.16 0.4 0.05 0.05],...
            'String','W',...
            'Callback',@(~,~)ClickButton('W', hEditInput,hEditOutput,23,rectRotator1,rectRotator2, rectRotator3));    
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.22 0.4 0.05 0.05],...
            'String','E',...
            'Callback',@(~,~)ClickButton('E', hEditInput,hEditOutput,5,rectRotator1,rectRotator2, rectRotator3));    

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.28 0.4 0.05 0.05],...
            'String','R',...
            'Callback',@(~,~)ClickButton('R', hEditInput,hEditOutput,18,rectRotator1,rectRotator2, rectRotator3)); 
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.34 0.4 0.05 0.05],...
            'String','T',...
            'Callback',@(~,~)ClickButton('T', hEditInput,hEditOutput,20,rectRotator1,rectRotator2, rectRotator3));       

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.40 0.4 0.05 0.05],...
            'String','Z',...
            'Callback',@(~,~)ClickButton('Z', hEditInput,hEditOutput,26,rectRotator1,rectRotator2, rectRotator3)); 
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.46 0.4 0.05 0.05],...
            'String','U',...
            'Callback',@(~,~)ClickButton('U', hEditInput,hEditOutput,21,rectRotator1,rectRotator2, rectRotator3)); 

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.52 0.4 0.05 0.05],...
            'String','I',...
            'Callback',@(~,~)ClickButton('I', hEditInput,hEditOutput,9,rectRotator1,rectRotator2, rectRotator3)); 
        
       uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.58 0.4 0.05 0.05],...
            'String','O',...
            'Callback',@(~,~)ClickButton('O', hEditInput,hEditOutput,15,rectRotator1,rectRotator2, rectRotator3)); 
       
        
      

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.16 0.34 0.05 0.05],...
            'String','A',...
            'Callback',@(~,~)ClickButton('A', hEditInput,hEditOutput,1,rectRotator1,rectRotator2, rectRotator3)); 
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.22 0.34 0.05 0.05],...
            'String','S',...
            'Callback',@(~,~)ClickButton('S', hEditInput,hEditOutput,19,rectRotator1,rectRotator2, rectRotator3));        

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.28 0.34 0.05 0.05],...
            'String','D',...
            'Callback',@(~,~)ClickButton('D', hEditInput,hEditOutput,4,rectRotator1,rectRotator2, rectRotator3)); 
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.34 0.34 0.05 0.05],...
            'String','F',...
            'Callback',@(~,~)ClickButton('F', hEditInput,hEditOutput,6,rectRotator1,rectRotator2, rectRotator3));   

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.40 0.34 0.05 0.05],...
            'String','G',...
            'Callback',@(~,~)ClickButton('G', hEditInput,hEditOutput,7,rectRotator1,rectRotator2, rectRotator3)); 
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.46 0.34 0.05 0.05],...
            'String','H',...
            'Callback',@(~,~)ClickButton('H', hEditInput,hEditOutput,8,rectRotator1,rectRotator2, rectRotator3));  

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.52 0.34 0.05 0.05],...
            'String','J',...
            'Callback',@(~,~)ClickButton('J', hEditInput,hEditOutput,10,rectRotator1,rectRotator2, rectRotator3)); 
        
       uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.58 0.34 0.05 0.05],...
            'String','K',...
            'Callback',@(~,~)ClickButton('K', hEditInput,hEditOutput,11,rectRotator1,rectRotator2, rectRotator3)); 
        
        uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.10 0.28 0.05 0.05],...
            'String','P',...
            'Callback',@(~,~)ClickButton('P', hEditInput,hEditOutput,16,rectRotator1,rectRotator2, rectRotator3));   

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.16 0.28 0.05 0.05],...
            'String','Y',...
            'Callback',@(~,~)ClickButton('Y', hEditInput,hEditOutput,25,rectRotator1,rectRotator2, rectRotator3)); 
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.22 0.28 0.05 0.05],...
            'String','X',...
            'Callback',@(~,~)ClickButton('X', hEditInput,hEditOutput,24,rectRotator1,rectRotator2, rectRotator3)); 
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.28 0.28 0.05 0.05],...
            'String','C',...
            'Callback',@(~,~)ClickButton('C', hEditInput,hEditOutput,3,rectRotator1,rectRotator2, rectRotator3)); 
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.34 0.28 0.05 0.05],...
            'String','V',...
            'Callback',@(~,~)ClickButton('V', hEditInput,hEditOutput,22,rectRotator1,rectRotator2, rectRotator3));      

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.40 0.28 0.05 0.05],...
            'String','B',...
            'Callback',@(~,~)ClickButton('B', hEditInput,hEditOutput,2,rectRotator1,rectRotator2, rectRotator3)); 
        
      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.46 0.28 0.05 0.05],...
            'String','N',...
            'Callback',@(~,~)ClickButton('N', hEditInput,hEditOutput,14,rectRotator1,rectRotator2, rectRotator3));  

      uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.52 0.28 0.05 0.05],...
            'String','M',...
            'Callback',@(~,~)ClickButton('M', hEditInput,hEditOutput,13,rectRotator1,rectRotator2, rectRotator3)); 
        
       uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.58 0.28 0.05 0.05],...
            'String','L',...
            'Callback',@(~,~)ClickButton('L', hEditInput,hEditOutput,12,rectRotator1,rectRotator2, rectRotator3)); 
        
      rectangle('Position',[-3. -3 4 0.9],'Curvature',0.2)
      %PlugBoard Letters
     plugA = annotation('textbox', 'Position', [0.135+0.02 0.195 .035 .03],'String', 'A',...
                    'BackgroundColor', 'r','HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
      plugB = annotation('textbox', 'Position', [.17+0.02  0.195 .035 .03],'String', 'B',...
                    'BackgroundColor', 'b','HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugC = annotation('textbox', 'Position', [.205+0.02  0.195 .035 .03],'String', 'C',...
                    'BackgroundColor', 'y','HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugD = annotation('textbox', 'Position', [.240+0.02  0.195 .035 .03],'String', 'D',...
                    'BackgroundColor', 'm','HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugE = annotation('textbox', 'Position', [.275+0.02  0.195 .035 .03],'String', 'E',...
                    'BackgroundColor', 'c','HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugF = annotation('textbox', 'Position', [.310+0.02  0.195 .035 .03],'String', 'F',...
                    'BackgroundColor', 'g', 'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugG = annotation('textbox', 'Position', [.345+0.02  0.195 .035 .03],'String', 'G',...
                     'BackgroundColor', [0.9, 0.3,0.9],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugI = annotation('textbox', 'Position', [.380+0.02  0.195 .035 .03],'String', 'I',...
                    'BackgroundColor', [1, 0.27,0.07], 'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugJ = annotation('textbox', 'Position', [.415+0.02  0.195 .035 .03],'String', 'J',...
                   'BackgroundColor', [0.53, 1,0.07],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
      plugK = annotation('textbox', 'Position', [.45+0.02  0.195 .035 .03],'String', 'K',...
                    'BackgroundColor', [0.3, 0.3,0.6],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugL = annotation('textbox', 'Position', [.485+0.02  0.195 .035 .03],'String', 'L',...
                    'BackgroundColor', [0.75, 0.34,1],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugU = annotation('textbox', 'Position', [.520+0.02  0.195 .035 .03],'String', 'U',...
                     'BackgroundColor', [0.75, 0.34,0.1],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugX = annotation('textbox', 'Position', [.555+0.02  0.195 .035 .03],'String', 'X',...
                    'BackgroundColor', [0.3, 0.94,1],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
    plugR = annotation('textbox', 'Position', [0.135+0.02 0.12 .035 .03],'String', 'R',...
                    'BackgroundColor', [0.3, 0.94,1],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
      plugW = annotation('textbox', 'Position', [.17+0.02  0.12 .035 .03],'String', 'W',...
                    'BackgroundColor', [0.9, 0.3,0.9],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugS = annotation('textbox', 'Position', [.205+0.02  0.12 .035 .03],'String', 'S',...
                    'BackgroundColor', 'g','HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugN = annotation('textbox', 'Position', [.240+0.02  0.12 .035 .03],'String', 'N',...
                    'BackgroundColor', 'm','HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugH = annotation('textbox', 'Position', [.275+0.02  0.12 .035 .03],'String', 'H',...
                    'BackgroundColor', 'y','HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugT = annotation('textbox', 'Position', [.310+0.02  0.12 .035 .03],'String', 'T',...
                    'BackgroundColor', [0.3, 0.3,0.6], 'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugZ = annotation('textbox', 'Position', [.345+0.02  0.12 .035 .03],'String', 'Z',...
                     'BackgroundColor', 'r','HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugY = annotation('textbox', 'Position', [.380+0.02  0.12 .035 .03],'String', 'Y',...
                    'BackgroundColor', [0.53, 1,0.07],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugV = annotation('textbox', 'Position', [.415+0.02  0.12 .035 .03],'String', 'V',...
                    'BackgroundColor', [0.75, 0.34,0.1],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
      plugM = annotation('textbox', 'Position', [.45+0.02  0.12 .035 .03],'String', 'M',...
                   'BackgroundColor', 'c', 'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugP = annotation('textbox', 'Position', [.485+0.02  0.12 .035 .03],'String', 'P',...
                   'BackgroundColor', 'b', 'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugQ = annotation('textbox', 'Position', [.520+0.02  0.12 .035 .03],'String', 'Q',...
                    'BackgroundColor', [0.75, 0.34,1], 'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     plugO = annotation('textbox', 'Position', [.555+0.02  0.12 .035 .03],'String', 'O',...
                    'BackgroundColor', [1, 0.27,0.07],'HorizontalAlignment', 'center',...
                     'VerticalAlignment', 'middle');
     
      axis off
      
  end